---
services:

    _defaults:
        autowire: true
        public: true

    _instanceof:
        Symfony\Launchpad\Core\Command:
            tags: [sflaunchpad.command]

    # Not working in a Phar (method glob() is used but it is not working in a phar)
    #Symfony\Launchpad\Command\:
    #    resource: ../src/Command/*

    # then we need to list them manually
    Symfony\Launchpad\Command\Rollback: ~
    Symfony\Launchpad\Command\Docker\Start: ~
    Symfony\Launchpad\Command\Docker\Stop: ~
    Symfony\Launchpad\Command\Docker\Up: ~
    Symfony\Launchpad\Command\Docker\Clean: ~
    Symfony\Launchpad\Command\Docker\Status: ~
    Symfony\Launchpad\Command\Docker\Enter: ~
    Symfony\Launchpad\Command\Docker\Logs: ~
    Symfony\Launchpad\Command\Docker\SymfonyRun: ~
    Symfony\Launchpad\Command\Docker\ComposerRun: ~

    # Self
    Symfony\Launchpad\Command\SelfUpdate:
        calls:
            - [setParameters, [ {release_url: "%github_release_url%"} ] ]

    # Docker
    Symfony\Launchpad\Command\Docker\Update:
        calls:
            - [setRequiredRecipes, [ [ 'composer_install' ] ] ]

    Symfony\Launchpad\Command\Docker\Build:
        calls:
            - [setRequiredRecipes, [ [ 'composer_install' ] ] ]

    Symfony\Launchpad\Command\Docker\Initialize:
        calls:
            - [setRequiredRecipes, [ [ 'composer_install', 'sf_install' ] ] ]

    Symfony\Launchpad\Command\Docker\InitializeSkeleton:
        calls:
            - [setRequiredRecipes, [ [ 'composer_install' ] ] ]

    Symfony\Launchpad\Command\Docker\Create:
        calls:
            - [setRequiredRecipes, [ [ 'composer_install', 'sf_create', 'import_dump' ] ] ]

    Symfony\Launchpad\Command\Docker\DumpData:
        calls:
            - [setRequiredRecipes, [ [ 'create_dump' ] ] ]

    Symfony\Launchpad\Command\Docker\ImportData:
        calls:
            - [setRequiredRecipes, [ [ 'import_dump' ] ] ]

    # Kubernetes
    Symfony\Launchpad\Command\Kubernetes\Build: ~
    Symfony\Launchpad\Command\Kubernetes\Deploy: ~
    Symfony\Launchpad\Command\Kubernetes\Enter: ~
    Symfony\Launchpad\Command\Kubernetes\Tunnel: ~
