---
parameters:
    # TODO: Replace
    github_release_url: "https://api.github.com/repos/sklimaszewski/launchpad/releases?draft=false&prerelease=false"

services:

    _defaults:
        autowire: true
        public:  true

    Symfony\Launchpad\Listener\ApplicationUpdate:
        arguments:
            - {release_url: "%github_release_url%"}
        tags:
            - { name: kernel.event_listener, event: console.command, method: onCommandAction }

    Symfony\Launchpad\Listener\CommandException:
        tags:
            - { name: kernel.event_listener, event: console.error, method: onExceptionAction }

    Symfony\Launchpad\Listener\CommandStart:
        tags:
            - { name: kernel.event_listener, event: console.command, method: onCommandAction }


    Symfony\Launchpad\Listener\CommandTerminate:
        tags:
            - { name: kernel.event_listener, event: console.terminate, method: onTerminateAction }

    Symfony\Launchpad\Core\ProjectStatusDumper: ~

    Symfony\Launchpad\Listener\OSXListener:
        class:
        arguments: [!tagged sflaunchpad.osx.optimizer]
        tags:
            - { name: kernel.event_listener, event: console.command, method: onCommandAction }

    # OSX OPTIMIZER
    Symfony\Launchpad\Core\OSX\Optimizer\D4M:
        tags: [sflaunchpad.osx.optimizer]

    Symfony\Launchpad\Core\OSX\Optimizer\NFSVolumes:
        tags: [sflaunchpad.osx.optimizer]
