{{- $dockerConfigValue := .Values.symfony.image.pullSecretConfig | quote }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "image-pull-secret") }}
{{- if $secret }}
{{- $dockerConfigValue = index $secret.data ".dockerconfigjson" }}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
    name: image-pull-secret
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: {{ $dockerConfigValue }}