{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: symfony-ingress
    labels:
        app: symfony
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
{{- if .Values.ingress.annotations }}
    annotations:
{{ toYaml .Values.ingress.annotations | indent 8 }}
{{- end }}
spec:
{{- if .Values.ingress.className }}
    ingressClassName: {{ .Values.ingress.className }}
{{- end }}
    rules:
        -
            host: {{ .Values.symfony.host | quote }}
            http:
                paths:
                    - path: /
                      backend:
                          serviceName: symfony
                          servicePort: 80
{{- end }}