apiVersion: v1
kind: ConfigMap
metadata:
    name: nginx-configmap
    labels:
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
data:
    nginx.conf: |-
{{ .Files.Get "config/nginx/nginx.conf" | indent 8 }}