apiVersion: v1
kind: Service
metadata:
    name: symfony
    labels:
        app: symfony
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
spec:
    type: ClusterIP
    ports:
        - port: 80
    selector:
        service: symfony