{{- $appSecretValue := (randAlpha 16) | b64enc | quote }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "symfony-secret") }}
{{- if $secret }}
{{- $appSecretValue = index $secret.data "app-secret" }}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
    name: symfony-secret
type: Opaque
data:
    app-secret: {{ $appSecretValue }}
    database-url: {{ printf "mysql://symfony:changeme@symfony-mariadb:3306/symfony?serverVersion=mariadb-10.1.1" | b64enc | quote }}