version: '3.7'
services:
    symfony:
        volumes:
            - "nfsmount:${PROJECTMAPPINGFOLDER}"
volumes:
    nfsmount:
        driver: local
        driver_opts:
            type: nfs
            o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
            device: ":${PROJECTCOMPOSEPATH}/"