version: '3.7'
services:
    nginx:
        image: 'nginx:stable-alpine'
        volumes:
            - '${PROJECTCOMPOSEPATH}/${PROVISIONINGFOLDERNAME}/dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
            - '${PROJECTCOMPOSEPATH}/${PROVISIONINGFOLDERNAME}/dev/nginx/entrypoint.bash:/entrypoint.bash:ro'
        depends_on:
            - symfony
        volumes_from:
            - 'symfony:ro'
        entrypoint: /entrypoint.bash
        ports:
            - '${PROJECTPORTPREFIX}080:80'
            - '${PROJECTPORTPREFIX}081:81'
        environment:
            - PROJECTMAPPINGFOLDER
    symfony:
        build:
            context: '../../'
            dockerfile: 'docker/dev/symfony/Dockerfile'
            target: base
        volumes:
            - '${PROJECTCOMPOSEPATH}/${PROVISIONINGFOLDERNAME}/dev/symfony/php.ini:/usr/local/etc/php/php.ini:ro'
            - '${PROJECTCOMPOSEPATH}:${PROJECTMAPPINGFOLDER}:rw'
            - '${HOST_COMPOSER_CACHE_DIR}:${COMPOSER_CACHE_DIR}:rw'
        shm_size: 754M
        environment:
            - COMPOSER_CACHE_DIR
            - PROJECTMAPPINGFOLDER
            - DEV_UID
            - DEV_GID
            - XDEBUG_ENABLED
            - XDEBUG_CONFIG=remote_host=172.17.0.1
            - PHP_IDE_CONFIG=serverName=symfony
            - DATABASE_PREFIXES=DATABASE
            - 'DATABASE_URL=mysql://root:dev@db:3306/symfony?serverVersion=mariadb-10.3.27'
            - SYMFONY_SECRET=SymfonyLaunchpad20Secret09Dev83ModeZ
            - APP_SECRET=SymfonyLaunchpad20Secret09Dev83ModeZ
            - CUSTOM_CACHE_POOL=singleredis
            - CACHE_HOST=redis
            - CACHE_REDIS_PORT=6379
            - CACHE_POOL=cache.redis
            - 'CACHE_DSN=redis:6379'
            - SYMFONY_TMP_DIR=/tmp/symfonycache/
            - APP_CACHE_DIR=/tmp/symfonycache/
            - APP_LOG_DIR=/tmp/symfonylogs/
            - SESSION_HANDLER_ID=symfony.core.session.handler.native_redis
            - 'SESSION_SAVE_PATH=tcp://redis:6379'
            - 'MAILER_DSN=smtp://mailcatcher:1025'
            - COMPOSER_MEMORY_LIMIT=-1
    db:
        image: 'mariadb:10.3'
        environment:
            - MYSQL_ROOT_PASSWORD=dev
        ports:
            - '${PROJECTPORTPREFIX}306:3306'
    mailcatcher:
        image: 'schickling/mailcatcher'
        ports:
            - '${PROJECTPORTPREFIX}180:1080'
    adminer:
        image: 'adminer:latest'
        ports:
            - '${PROJECTPORTPREFIX}084:8080'
    redis:
        image: 'redis:latest'
        depends_on:
            - symfony
    redisadmin:
        image: 'rediscommander/redis-commander:latest'
        environment:
            - REDIS_HOST=redis
        ports:
            - '${PROJECTPORTPREFIX}083:8081'
